validator:
  build: .
  ports:
    - "8080:8080"
  volumes:
    - "$HOME/.boot2docker/certs/boot2docker-vm:/boot2docker:ro"
  environment:
    DEBUG: "index,validation,fetcher"
    port: 8080
    tmp: ""
    "docker:cert": /boot2docker/cert.pem
    "docker:key": /boot2docker/key.pem
    "docker:ca": /boot2docker/ca.pem
